name: Release

on:
  push:
    branches:
      - "d3fc-v6-latest"
      - "d3fc-v7-latest"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-test-lint:
    name: Build, test, and lint
    uses: ./.github/workflows/development.yml

  changelog:
    name: Generate changelog and version PRs
    if: github.repository == 'defnotjec/d3fc'
    needs: build-test-lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: "Install dependencies"
        run: npm ci

      - name: "Running build"
        run: npm run build

      - name: "Create version PR / changelog"
        uses: changesets/action@v1
        with:
          title: "chore: version packages"
          commit: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
